export const style = ["Doodling",
"Photorealism",
"Hyperrealism",
"Cartoon style",
"Line drawing",
"Architectural drawing",
"Fashion illustration",
"Cross-contour drawing",
"Quick sketches",
"Minimalist drawing",
"Caricature drawing",
"3D drawing",
"Geometric drawing",
"Tattoo drawing",
"Typography drawing",
"Stippling",
"Hatching and cross-hatching",
"Scumbling",
"Scribble art",
"Diagrammatic drawing",
"Anamorphic drawing"]