export const style = [
  'Gribouillage',
  'Réalisme photographique',
  'Hyper-réalisme',
  'Style de dessin animé',
  'Tracé en ligne',
  'Dessin architectural',
  'Illustration de mode',
  'Dessin en contour croisé',
  'Croquis rapides',
  'Dessin minimaliste',
  'Dessin de caricature',
  'Dessin en 3D',
  'Dessin géométrique',
  'Dessin de tatouage',
  'Dessin typographique',
  'Stippling (pointillisme)',
  'Hachures et hachures croisées',
  'Estompage',
  'Art griffonné',
  'Dessin diagrammatique',
  'Dessin anamorphique'
]
