export const subjects = [
    'Un personnage fantastique',
    'Un paysage urbain',
    'Des animaux mignons',
    'Des objets futuristes',
    'Un portrait réaliste',
    'La nature sauvage',
    'Une créature mythologique',
    'Une scène de bataille',
    'Une ville médiévale',
    'Des super-héros en action',
    'Un comique',
    'Un personnage historique',
    'Un robot intelligent',
    'Un voyage dans le temps',
    'Des monstres effrayants',
    'Une architecture moderne',
    'Une scène de crime',
    'Un astronaute dans l\'espace',
    'Un fantôme hantant',
    'Un voyage en forêt',
    'Un personnage de conte de fées',
    'Un véhicule de rêve',
    'Un portrait de célébrité',
    'Une planète lointaine',
    'Une exploration sous-marine',
    'Un alien exotique',
    'Une scène de guerre',
    'Une exploration de grotte',
    'Un animal en voie de disparition',
    'Des objets magiques',
    'Une jungle luxuriante',
    'Un robot géant',
    'Un voyage en montgolfière',
    'Un paysage hivernal',
    'Un personnage futuriste',
    'Une planète extraterrestre',
    'Une bataille spatiale',
    'Un voyage en train à vapeur',
    'Une créature légendaire',
    'Une scène de danse',
    'Un voyage en montagne',
    'Un personnage de conte',
    'Un engin spatial',
    'Une créature aquatique',
    'Un village médiéval',
    'Un avion de chasse',
    'Un portrait de famille',
    'Un voyage en jungle',
    'Un personnage de jeu vidéo',
    'Un objet antique',
    'Un voyage en désert',
    'Un voyage en sous-marin',
    'Une créature extraterrestre',
    'Un paysage fantastique',
    'Un personnage de bande dessinée',
    'Une machine à remonter le temps',
    'Un pirate sur un navire',
    'Un voyage en canyon',
    'Un personnage de science-fiction',
    'Une ville futuriste',
    'Une créature magique',
    'Une scène de course-poursuite',
    'Un voyage en vaisseau spatial',
    'Un personnage historique célèbre',
    'Un paysage aquatique',
    'Un robot domestique',
    'Un voyage en forêt enchantée',
    'La lutte contre les zombies',
    'Un personnage de conte célèbre',
    'Une planète alien habitée',
    'Un atterrissage sur Mars',
    'Un personnage de dessin animé',
    'Un objet technologique avancé',
    'Un voyage dans un monde parallèle',
    'Une exploration de l\'océan profond',
    'Un alien pacifique',
    'Une scène de bataille épique',
    'Un voyage en train à grande vitesse',
    'Un portrait d\'animal sauvage',
    'Un personnage légendaire',
    'Un voyage en navette spatiale',
    'Une créature sous-marine fantastique',
    'Un village médiéval en fête',
    'Un objet magique ancien',
    'Un voyage en montagne enneigée',
    'Un personnage de jeu vidéo rétro',
    'Un avion de chasse en mission',
    'Un portrait de groupe',
    'Un voyage en jungle tropicale',
    'Un personnage de bande dessinée préféré',
    'Un objet antique précieux',
    'Un voyage dans le désert aride',
    'Une exploration sous-marine mystérieuse',
    'Une créature extraterrestre amicale',
    'Un paysage fantastique onirique',
    'Un héros de bande dessinée',
    'Une machine à voyager dans le temps',
    'Une chasse au trésor pirate',
    'Un voyage en canyon spectaculaire',
    'Un personnage de science-fiction classique',
    'Une métropole futuriste',
    'Une créature mythique rare',
    'Une scène de course-poursuite effrénée',
    'Un voyage interstellaire',
    'Un portrait de personnage historique',
    'Une mystérieuse cité sous-marine',
    'Un alien artistique',
    'Une bataille galactique épique',
    'Un voyage en train à vapeur rétro',
    'Un portrait d\'animaux exotiques',
    'Un personnage mythologique',
    'Une exploration spatiale en vaisseau',
    'Une créature marine légendaire',
    'Un village médiéval animé',
    'Un objet magique enchanté',
    'Un voyage en montagne majestueuse',
    'Un personnage de jeu d\'arcade',
    'Un dogfight aérien',
    'Un portrait de famille chaleureux',
    'Une aventure en jungle inexplorée',
    'Un personnage de dessin animé nostalgique',
    'Une relique ancienne mystérieuse',
];
