export const subjects = [
    'Personnage fantastique',
    'Paysage urbain',
    'Animaux mignons',
    'Objets futuristes',
    'Portrait réaliste',
    'Nature sauvage',
    'Créature mythologique',
    'Scène de bataille',
    'Ville médiévale',
    'Super-héros en action',
    'Comique',
    'Personnage historique',
    'Robot intelligent',
    'Voyage dans le temps',
    'Monstres effrayants',
    'Architecture moderne',
    'Scène de crime',
    'Astronaute dans l\'espace',
    'Fantôme hantant',
    'Voyage en forêt',
    'Personnage de conte de fées',
    'Véhicule de rêve',
    'Portrait de célébrité',
    'Planète lointaine',
    'Exploration sous-marine',
    'Alien exotique',
    'Scène de guerre',
    'Exploration de grotte',
    'Animal en voie de disparition',
    'Objets magiques',
    'Jungle luxuriante',
    'Robot géant',
    'Voyage en montgolfière',
    'Paysage hivernal',
    'Personnage futuriste',
    'Planète extraterrestre',
    'Bataille spatiale',
    'Voyage en train à vapeur',
    'Créature légendaire',
    'Scène de danse',
    'Voyage en montagne',
    'Personnage de conte',
    'Engin spatial',
    'Créature aquatique',
    'Village médiéval',
    'Avion de chasse',
    'Portrait de famille',
    'Voyage en jungle',
    'Personnage de jeu vidéo',
    'Objet antique',
    'Voyage en désert',
    'Voyage en sous-marin',
    'Créature extraterrestre',
    'Paysage fantastique',
    'Personnage de bande dessinée',
    'Machine à remonter le temps',
    'Pirate sur un navire',
    'Voyage en canyon',
    'Personnage de science-fiction',
    'Ville futuriste',
    'Créature magique',
    'Scène de course-poursuite',
    'Voyage en vaisseau spatial',
    'Personnage historique célèbre',
    'Paysage aquatique',
    'Robot domestique',
    'Voyage en forêt enchantée',
    'Lutte contre les zombies',
    'Personnage de conte célèbre',
    'Planète alien habitée',
    'Atterrissage sur Mars',
    'Personnage de dessin animé',
    'Objet technologique avancé',
    'Voyage dans un monde parallèle',
    'Exploration de l\'océan profond',
    'Alien pacifique',
    'Scène de bataille épique',
    'Voyage en train à grande vitesse',
    'Portrait d\'animal sauvage',
    'Personnage légendaire',
    'Voyage en navette spatiale',
    'Créature sous-marine fantastique',
    'Village médiéval en fête',
    'Objet magique ancien',
    'Voyage en montagne enneigée',
    'Personnage de jeu vidéo rétro',
    'Avion de chasse en mission',
    'Portrait de groupe',
    'Voyage en jungle tropicale',
    'Personnage de bande dessinée préféré',
    'Objet antique précieux',
    'Voyage dans le désert aride',
    'Exploration sous-marine mystérieuse',
    'Créature extraterrestre amicale',
    'Paysage fantastique onirique',
    'Héros de bande dessinée',
    'Machine à voyager dans le temps',
    'Chasse au trésor pirate',
    'Voyage en canyon spectaculaire',
    'Personnage de science-fiction classique',
    'Métropole futuriste',
    'Créature mythique rare',
    'Scène de course-poursuite effrénée',
    'Voyage interstellaire',
    'Portrait de personnage historique',
    'Mystérieuse cité sous-marine',
    'Alien artistique',
    'Bataille galactique épique',
    'Voyage en train à vapeur rétro',
    'Portrait d\'animaux exotiques',
    'Personnage mythologique',
    'Exploration spatiale en vaisseau',
    'Créature marine légendaire',
    'Village médiéval animé',
    'Objet magique enchanté',
    'Voyage en montagne majestueuse',
    'Personnage de jeu d\'arcade',
    'Dogfight aérien',
    'Portrait de famille chaleureux',
    'Aventure en jungle inexplorée',
    'Personnage de dessin animé nostalgique',
    'Relique ancienne mystérieuse',
];
