export const themes = [
    'Fantaisie',
    'Science-fiction',
    'Réaliste',
    'Autre',
    'Aventure',
    'Mystère',
    'Horreur',
    'Romance',
    'Historique',
    'Action',
    'Comédie',
    'Drame',
    'Suspense',
    'Thriller',
    'Magie',
    'Super-héros',
    'Post-apocalyptique',
    'Contemporain',
    'Espionnage',
    'Western',
    'Cyberpunk',
    'Surnaturel',
    'Épique',
    'Enquête',
    'Guerre',
    'Voyage dans le temps',
    'Extraterrestres',
    'Contes de fées',
    'Dystopie',
    'Policier',
    'Fantômes',
    'Survie',
    'Animaux',
    'Futuriste',
    'Uchronie',
    'Steampunk',
    'Mythologie',
    'Informatique',
    'Apocalyptique',
    'Voyage spatial',
    'Environnement',
    'Art',
    'Magiciens',
    'Technologie',
    'Espionnage',
    'Nature',
    'Religieux',
    'Scolaire',
    'Amour interdit',
    'Course poursuite',
    'Conspiration',
    'Musique',
    'Famille'
];
